# documentation at https://docs.platformio.org/en/latest/integration/ci/github-actions.html

name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [
          examples/dsk_LoRaE5_SimpleUplink/dsk_LoRaE5_SimpleUplink.ino,
          examples/dsk_LoRaE5_StoreCredentials/dsk_LoRaE5_StoreCredentials.ino, 
          examples/dsk_LoRaE5_UplinkDownlink/dsk_LoRaE5_UplinkDownlink.ino
          ]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio ci --lib="." --board=esp-wrover-kit
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}